branch-defaults:
  master:
    environment: gsgSignup-nagzs-env
environment-defaults:
  gsgSignup-nagzs-env:
    branch: null
    repository: null
global:
  application_name: gsg-signup
  default_ec2_keyname: instance20march
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.5
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
